version: '3.8'

services:
  python-app:
    build: .  # Build the image from the Dockerfile in the current directory
    container_name: python_app
    environment:
      # Pass the hostname of the RabbitMQ service to the Python app
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      # Wait for the rabbitmq service to be healthy before starting
      - rabbitmq
    networks:
      - app-network

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol
      - "15672:15672" # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
