version: '3.9'

services:
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_123
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - auth-net

volumes:
  auth-db-data:

networks:
  auth-net:
    name: auth-net   # garante que a rede tenha nome fixo

