version: '3.9'

services:
  auth-service:
    build: .
    environment:
      DB_HOST: auth-db   # mesmo nome do service no db.yml
      DB_PORT: 5432
      DB_NAME: auth_db
      DB_USER: auth_user
      DB_PASS: secret_auth
    depends_on:
      - auth-db
    ports:
      - "8081:8081"
    networks:
      - auth-net

networks:
  auth-net:
    external: true   # usa a rede jรก criada pelo outro compose

